#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCLUDE_DIRS = {'.git', '.obsidian', 'assets', 'node_modules'}
OUT = ROOT / '_docs' / 'vault-qc-audit.json'
REPORT = ROOT / '_docs' / 'VAULT-QC-AUDIT.md'

def iter_md():
    for p in ROOT.rglob('*.md'):
        if any(part in EXCLUDE_DIRS for part in p.parts):
            continue
        yield p

def parse_frontmatter(text: str):
    fm = {}
    body = text
    if text.startswith('---'):
        parts = text.split('---', 2)
        if len(parts) >= 3:
            raw = parts[1]
            body = parts[2]
            current = None
            for line in raw.splitlines():
                if not line.strip():
                    continue
                if re.match(r'^[A-Za-z0-9_-]+:', line):
                    k, v = line.split(':', 1)
                    current = k.strip()
                    fm[current] = v.strip()
                elif current:
                    fm[current] += '\n' + line
    return fm, body

def title_value(v: str) -> str:
    return v.strip().strip('"').strip("'")

def word_count(s: str) -> int:
    return len(re.findall(r"[\wÀ-ỹ]+", s, flags=re.UNICODE))

def is_public_note(p: Path) -> bool:
    rel = p.relative_to(ROOT)
    if rel.parts[0] == '_docs':
        return False
    if rel.name.startswith('.') or rel.name.lower() in {'readme.md', 'claude.md'}:
        return False
    return True

def main():
    notes = []
    titles = defaultdict(list)
    issues = {
        'missing_description': [],
        'missing_aliases': [],
        'thin_lt800': [],
        'duplicate_titles': [],
        'mobile_hostile_code': [],
        'horizontal_chain': [],
        'textblock_candidates': [],
        'broken_links': [],
        'orphans_public': [],
    }
    for p in iter_md():
        rel = p.relative_to(ROOT).as_posix()
        text = p.read_text(errors='ignore')
        fm, body = parse_frontmatter(text)
        title = title_value(fm.get('title', '')) or p.stem
        aliases = fm.get('aliases', '').strip()
        desc = fm.get('description', '').strip()
        words = word_count(body)
        public = is_public_note(p)
        notes.append({'path': rel, 'title': title, 'words': words, 'public': public})
        titles[title].append(rel)
        if public and not desc:
            issues['missing_description'].append(rel)
        if public and not aliases:
            issues['missing_aliases'].append(rel)
        if public and words < 800:
            issues['thin_lt800'].append({'path': rel, 'words': words})
        if public and ('```text' in text or re.search(r'`[^`\n]{90,}`', text)):
            issues['mobile_hostile_code'].append(rel)
        if public and re.search(r'[^\n]{0,80}(→|->|=>)[^\n]{40,}(→|->|=>)', text):
            issues['horizontal_chain'].append(rel)
        paras = [x.strip() for x in body.split('\n\n') if x.strip() and not x.strip().startswith(('#','-','|','>','```','---'))]
        if public and len(paras) >= 12:
            short = sum(1 for x in paras if len(x) < 90)
            ratio = short / len(paras)
            if ratio > 0.35:
                issues['textblock_candidates'].append({'path': rel, 'short': short, 'paragraphs': len(paras), 'ratio': round(ratio, 3)})

    for title, paths in titles.items():
        pubs = [p for p in paths if not p.startswith('_docs/')]
        if len(pubs) > 1:
            issues['duplicate_titles'].append({'title': title, 'paths': pubs})

    km = ROOT / '_docs' / 'knowledge-map.json'
    if km.exists():
        data = json.loads(km.read_text())
        issues['broken_links'] = data.get('brokenLinks', [])
        issues['orphans_public'] = [o for o in data.get('orphans', []) if not str(o.get('path','')).startswith('_docs/')]

    public_notes = [n for n in notes if n['public']]
    summary = {
        'public_notes': len(public_notes),
        'avg_words': round(sum(n['words'] for n in public_notes) / max(1, len(public_notes))),
        'missing_description': len(issues['missing_description']),
        'missing_aliases': len(issues['missing_aliases']),
        'thin_lt800': len(issues['thin_lt800']),
        'duplicate_titles': len(issues['duplicate_titles']),
        'mobile_hostile_code': len(issues['mobile_hostile_code']),
        'horizontal_chain': len(issues['horizontal_chain']),
        'textblock_candidates': len(issues['textblock_candidates']),
        'broken_links': len(issues['broken_links']),
        'orphans_public': len(issues['orphans_public']),
    }
    payload = {'summary': summary, 'issues': issues}
    OUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2))

    lines = ['# Vault QC Audit', '', 'Generated by `scripts/vault_qc_audit.py`.', '', '## Summary', '']
    for k, v in summary.items():
        lines.append(f'- **{k}**: {v}')
    lines += ['', '## Priority issue samples', '']
    for key in ['broken_links','duplicate_titles','horizontal_chain','mobile_hostile_code','textblock_candidates','missing_aliases','thin_lt800','orphans_public']:
        vals = issues[key]
        lines += [f'### {key}', '']
        if not vals:
            lines.append('- none')
        else:
            for item in vals[:25]:
                if isinstance(item, dict):
                    lines.append(f'- `{item.get("path") or item.get("source") or item.get("title")}` — {item}')
                else:
                    lines.append(f'- `{item}`')
        lines.append('')
    REPORT.write_text('\n'.join(lines) + '\n')
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print(f'Wrote {OUT.relative_to(ROOT)}')
    print(f'Wrote {REPORT.relative_to(ROOT)}')

if __name__ == '__main__':
    main()
